# Generated by Django 4.1.6 on 2023-02-20 23:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationsMessage',
            new_name='ConversationMessage',
        ),
    ]
